version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"    
  test.api:
    image: ${DOCKER_REGISTRY}testapi
    build:
      context: .
      dockerfile: src/Test.Api/Dockerfile
  test.services.SLMM:
    image: ${DOCKER_REGISTRY}testservicesSLMM
    build:
      context: .
      dockerfile: src/Test.Services.Contest/Dockerfile